### ISSUE TITLE
WebSocket とかで自動更新

### ISSUE THREAD

**Issue by daimatz** [daimatz/mamemose#2]
WebSocket で自動更新できると嬉しい

**Comment by kaorimatz** [comment]
ブラウザの自動更新には http://nitoyon.github.com/livereloadx/ を使っています。

```
$ livereloadx $DOCUMENTS
```

として、livereloadx にドキュメントを置いている `$DOCUMENTS` を監視させておき、`.mamemose.rb` に

``` ruby
CUSTOM_FOOTER = <<FOOTER
<script src="http://localhost:35729/livereload.js?snipver=2"></script>
FOOTER
```

のように記述すると、ブラウザでメモを開いている状態でドキュメントを変更すると自動で更新してくれます。

ただ、今のところ
- ブラウザで開いているメモ以外の `$DOCUMENTS` 以下のファイルを変更しても自動更新しようとする
- 一時ファイル閲覧時には上記では自動更新できない

といった問題があります。

mamemose が自動更新をサポートする場合は上記の問題が発生しないと思うのでとても嬉しいですが、私の環境では livereloadx を使用する方法である程度上手く動いてくれていますので、もしかしたら参考になればと。

**Comment by daimatz** [comment]
おー、ありがとうございます。
言われてみればなるほどだけど、こんなこと考える人もいるんだねえ。
調べてみたところ WebSocket 対応もそこまで難しくなさそうなので、チャチャッとやってしまおうかと思います。

**Comment by daimatz** [comment]
v0.4.0 で対応

**Comment by kaorimatz** [comment]
快適です!
